title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "WueWoWas2022" # the subpath of your site, e.g. /blog

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"


# Theme configuration
logo: "/assets/images/i3.png"

atom_feed:
  hide: true

plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      excerpt: "Würzburg Workshop on XYZ<br>12 - 17 July 2022"
      header:
        overlay_image: /assets/images/wue_header2.jpg
        actions:
          - label: "News"
            url: "/news/"  
